spring.datasource.url=jdbc:mysql://localhost:3306/librarydb?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
spring.datasource.username=librarydb
spring.datasource.password=library123!

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update